language: generic
dist: trusty

env:
  - IMAGE_TO_BUILD=prestodev/hdp2.6-hive-kerberized IMAGE_TO_TEST=hdp2.6-hive
  - IMAGE_TO_BUILD=prestodev/hdp2.6-hive-kerberized-2
  - IMAGE_TO_BUILD=prestodev/hdp3.1-hive-kerberized IMAGE_TO_TEST=hdp3.1-hive
  - IMAGE_TO_BUILD=prestodev/cdh5.12-hive-kerberized IMAGE_TO_TEST=cdh5.12-hive
  - IMAGE_TO_BUILD=prestodev/cdh5.15-hive-kerberized-kms IMAGE_TO_TEST=cdh5.15-hive
  - IMAGE_TO_BUILD=prestodev/iop4.2-hive IMAGE_TO_TEST=iop4.2-hive
  - IMAGE_TO_BUILD=prestodev/spark3.0-iceberg
  - IMAGE_TO_BUILD=prestodev/centos6-oj8-openldap-referrals
  - IMAGE_TO_BUILD=prestodev/centos6-presto-admin-tests-build
  - IMAGE_TO_BUILD=prestodev/centos7-oj11
  - IMAGE_TO_BUILD=prestodev/dns
  - IMAGE_TO_BUILD=prestodev/kerberos TEST_COMMAND=bin/test_kerberos.sh

services:
  - docker

install: make ${IMAGE_TO_BUILD}

script:
  - |
    if [[ -v IMAGE_TO_TEST ]]; then
      make test IMAGE_TO_TEST=${IMAGE_TO_TEST}
    fi
  - |
    if [[ -v TEST_COMMAND ]]; then
      $TEST_COMMAND
    fi
